### ISSUE TITLE
New config variable: files_pdfviewer.enableScripting

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1245] opened 2024-01-15 18:26 UTC
## WHAT Needs to be Documented?

There is a new config parameter for the PDF viewer app

## WHERE Does This Need To Be Documented (Link)?

core config apps sample php, and possibly elsewhere in apps documenation?

References:
- https://github.com/owncloud/files_pdfviewer/issues/332#issuecomment-1892632347
- https://github.com/owncloud/files_pdfviewer/pull/331/files#diff-a1dedb2c63ef1dc17c3add0c4bff4691baf93165f3a9d3150374efbc88d85a37R7

**Comment by mmattel** [comment] 2024-01-27 15:37
Duplicate of #1247 
Closed via #1219

**Closed by mmattel** 2024-01-27 15:37 UTC
