### ISSUE TITLE
Full text search not fully documented

### ISSUE THREAD

**Issue by xoxys** [owncloud/docs-server#526] opened 2022-07-13 09:47 UTC
## WHAT Needs to be Documented?
Missing admin information from https://github.com/owncloud/search_elastic e.g. `App Mode`

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/latest/admin_manual/configuration/general_topics/search.html

## WHY Should This Change Be Made?
Because it's missing,

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment] 2022-07-13 11:37
Thanks
Duplicate of #101
I am just working on it,
Closing

**Closed** 2022-07-13 11:38 UTC

**Comment by xoxys** [comment] 2022-07-13 12:09
Well the other issue is not mentioning anything from the readme, but if you remember to add it, fine for me.
